# Generated by Django 4.1 on 2023-01-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.URLField(null=True),
        ),
    ]
